# Generated by Django 5.0.3 on 2024-04-02 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='short_id',
            field=models.CharField(default='TEST', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]+$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Student'), (2, 'Teacher'), (3, 'Secretary'), (4, 'Study Student')], null=True),
        ),
    ]
