# Generated by Django 5.0.3 on 2024-04-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_school_short_id_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Teacher'), (2, 'Secretary'), (3, 'Admin')], null=True),
        ),
    ]
