# Generated by Django 5.0.3 on 2024-04-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_study_student_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_access_group',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'English'), (2, 'French')], null=True),
        ),
    ]
