# Generated by Django 5.0.3 on 2024-04-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_course_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='english_since_grade',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='school',
            name='french_since_grade',
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]
