# Generated by Django 4.2.11 on 2024-04-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_school_english_since_grade_school_french_since_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='study_started',
            field=models.BooleanField(default=False),
        ),
    ]
