# Generated by Django 4.2.11 on 2024-05-26 10:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_course_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangedUsernames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_username', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='E-Mail Adresse')),
                ('new_username', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='E-Mail Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
