# Generated by Django 4.2.11 on 2024-07-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='downloaded_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='finished_study',
            field=models.BooleanField(default=False),
        ),
    ]
