# Generated by Django 5.0.3 on 2024-04-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_usertodo_completed_usertodo_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardtodo',
            name='action_relative_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
