# Generated by Django 4.2.11 on 2024-04-30 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_standardtodo_action_relative_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertodo',
            name='activation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
