# Generated by Django 4.2.11 on 2024-04-30 14:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_course_start_date_course_study_started'),
        ('todo', '0004_usertodo_activation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertodo',
            name='activation_date',
        ),
        migrations.RemoveField(
            model_name='usertodo',
            name='due_date',
        ),
        migrations.CreateModel(
            name='ToDoDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('activation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_dates', to='accounts.course')),
                ('standard_todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_dates', to='todo.standardtodo')),
            ],
        ),
    ]
