# Generated by Django 5.0.3 on 2024-04-11 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studydata', '0002_alter_firstquestionnaire_pronunciation_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstquestionnaire',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
