# Generated by Django 5.0.3 on 2024-04-18 11:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studydata', '0003_alter_firstquestionnaire_age'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('language', models.PositiveSmallIntegerField(choices=[(1, 'English'), (2, 'French')])),
                ('synth_filepath', models.FilePathField(blank=True, default=None, null=True)),
                ('number_of_times_assigned', models.PositiveIntegerField(default=0)),
                ('number_of_times_completed', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PronunciationAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('sentence_id', models.IntegerField()),
                ('recognized_sentence', models.TextField(blank=True, null=True)),
                ('language', models.PositiveSmallIntegerField(choices=[(1, 'English'), (2, 'French')])),
                ('accuracy', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('completeness', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('fluency', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('full_result', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
