# Generated by Django 5.0.3 on 2024-04-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studydata', '0004_studysentences_pronunciationassessmentresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysentences',
            name='synth_filepath',
        ),
        migrations.AddField(
            model_name='studysentences',
            name='synth_filename',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studysentences',
            name='sentence',
            field=models.TextField(unique=True),
        ),
    ]
