# Generated by Django 5.0.3 on 2024-04-18 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studydata', '0005_remove_studysentences_synth_filepath_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pronunciationassessmentresult',
            name='sentence_id',
        ),
        migrations.AddField(
            model_name='pronunciationassessmentresult',
            name='sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studydata.studysentences'),
        ),
    ]
