# Generated by Django 4.2.11 on 2024-04-27 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_school_english_since_grade_school_french_since_grade'),
        ('studydata', '0006_remove_pronunciationassessmentresult_sentence_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studysentences',
            old_name='number_of_times_assigned',
            new_name='number_of_times_assigned_as_test',
        ),
        migrations.RenameField(
            model_name='studysentences',
            old_name='number_of_times_completed',
            new_name='number_of_times_assigned_as_train',
        ),
        migrations.CreateModel(
            name='StudySentencesCourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_value', models.PositiveSmallIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studydata.studysentences')),
            ],
        ),
    ]
