# Generated by Django 4.2.11 on 2024-05-06 16:16

import backend.custom_storages
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studydata', '0008_finalquestionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSentencesWithAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(storage=backend.custom_storages.PrivateMediaStorage(), upload_to='student_audio_files/')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studydata.studysentences')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
