# Generated by Django 4.2.11 on 2024-05-12 12:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_course_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studydata', '0010_remove_testsentenceswithaudio_audio_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySentenceByWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_index', models.PositiveSmallIntegerField()),
                ('accuracy_score', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studydata.studysentences')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
