# Generated by Django 4.2.11 on 2024-06-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studydata', '0013_rename_full_result_pronunciationassessmentresult_json_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsentenceswithaudio',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
